name: Build Switch Homebrew

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup devkitPro repository
        run: |
          # Добавляем официальный репозиторий devkitPro
          echo "Server = https://downloads.devkitpro.org/packages" > /etc/pacman.d/dkp-mirrorlist
          echo "Server = https://www.mirrorservice.org/sites/downloads.devkitpro.org/packages" >> /etc/pacman.d/dkp-mirrorlist
          # Обновляем список пакетов
          pacman -Syy

      - name: Install dependencies
        run: |
          # Устанавливаем необходимые библиотеки
          dkp-pacman -S --noconfirm switch-libnx switch-libdeko3d switch-libimgui

      - name: Build project
        run: |
          make -j8

      - name: Upload .nro artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromium-switch
          path: chromium_switch.nro
